name: ainsighter
description: Ainsighter mobil uygulaması

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.4+19

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  provider: ^6.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  image_picker: ^0.8.3+2
  connectivity: ^3.0.6
  http: ^0.13.3
  fluro: ^2.0.3
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  simple_animations: ^2.0.0
  shimmer_animation: ^2.1.0+1
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0 
  lottie: ^1.1.0
  get_it: ^7.2.0 
  curved_navigation_bar: ^1.0.1 
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.16 
  flutter_staggered_grid_view: ^0.4.1 
  flutter_share: ^2.0.0   
  flutter_neumorphic: ^3.0.3
  flutter_easyloading: ^3.0.5 
  scroll_to_index: ^3.0.1
  drop_shadow: ^0.0.1+4
  store_redirect: ^2.0.1
  simple_shadow: ^0.3.0
  gallery_saver: ^2.3.2 
  flutter_native_image: ^0.0.6+1
  platform_device_id: ^1.0.1
  flutter_cache_manager: ^3.3.0
  onesignal_flutter: 3.4.1
  firebase_core: ^2.4.0 
  firebase_messaging: ^14.2.0
  firebase_crashlytics: ^3.0.8
  firebase_performance: ^0.9.0+8
  firebase_in_app_messaging: ^0.7.0+9
  google_mlkit_face_detection: ^0.5.0  
  image_gallery_saver: ^1.7.1
  grouped_list: ^5.1.2
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.12
  image: ^3.1.3
  fast_image_resizer: ^0.0.2
  like_button: ^2.0.5
  assorted_layout_widgets: ^7.0.0
  purchases_flutter: ^4.10.2
  easy_localization: ^3.0.1 
  flutter_onboarding_slider:
    path: packages/flutter_onboarding_slider
  image_cropper:
    path: packages/image_cropper 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/animations/
    - assets/icons/ 
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
